### ISSUE TITLE
stickyHeaderIndices not working like in FlatList

### ISSUE THREAD

**Issue by rvasseur31** [Shopify/flash-list#484]
Hello,

To start, I just wanted to say thank you to all the people who worked on this library, the library is very awesome 🤩 !

I use the props stickyHeaderIndices={[0]} to stick the ListHeaderComponent prop to the top of the list

With React Native FlatList, it work like I want :

<img width="351" alt="image" src="https://user-images.githubusercontent.com/46020438/176848003-5a4e83e4-4364-49fd-bc80-8fc2bc340b35.png">

With Shopify Flash List, the value in stickyHeaderIndices only applies to the list item and not ListHeaderComponent :

<img width="350" alt="image" src="https://user-images.githubusercontent.com/46020438/176848073-e475674c-0dad-4513-9f49-a7a02fc1f7a9.png">

**Comment by naqvitalha** [comment]
This is by design. 

Let's say you make index 5 sticky and later you add a header, suddenly the index needs to be 6 instead. We did not like this implicit behaviour.

Moving header out of the list is simple anyway if you don't want it to scroll.

**Comment by elliottkember** [comment]
> Can't we just keep the header outside of the list to get the same behavior?

With a floating header, the content scrolls underneath the header and the contentContainer offset is set automatically to the sticky header's height. You could do this with the header outside the list - it's just trickier as we'd have to use an onLayout callback on the header to calculate the list's content offset. 

Like this: https://user-images.githubusercontent.com/42827/181918120-a3def8dd-c248-49eb-aa84-2ee21d5f8183.MOV

Migrating from FlatList was otherwise relatively painless, but this difference was unexpected to me so I ended up removing the library for now.

**Comment by naqvitalha** [comment]
Well, you can render the header outside the list with absolute position and also pass it to the list with opacity 0 to get the same effect. It's a minor component so rendering twice should be fine and you won't need to compute the offset.

**Comment by naqvitalha** [comment]
Nope, just pass it as header with opacity 0 and also render outside list with position absolute
