### ISSUE TITLE
ViewableItems not working with FlashList

### ISSUE THREAD

**Issue by brunolcarlos** [Shopify/flash-list#566]
With FlatList and react-native-big-list the ViewableItems works fine but with FlashList does't works

When the items change the FlashList it's not passing the new state to Component inside of the renderItem

How can I fix It ?

This is a Android APP expo 46 and Expo GO

```
const onViewRef = React.useRef(({ viewableItems, changed }) => {
    if (viewableItems && viewableItems.length > 0) {
      setItemState(viewableItems[0]);
    }
  });

  const viewConfigRef = React.useRef({
    viewAreaCoveragePercentThreshold: 50,
  });

 const keyExtractor = useCallback(
    (item, index) => `${item.hash}${index}${item.post_id}`,
    []
  );

  const renderItemFinal = ({ item, index }) => {
    if (item?.post_type == "video") {
      return (
        <Video
          patrocinado={item?.patrocinado}
          index={index * page}
          userStorage={userStorage}
          postUnlike={postUnlike}
          postLike={postLike}
          onViewRef={
            itemState?.item?.post_id == item?.post_id && itemState?.isViewable
              ? true
              : false
          }
          item={item}
        />
      );
    }
  };

 const itemRender= useMemo(() => renderItemFinal, [itemState]);


 <FlashList
    refreshControl={refreshingjsx}
    data={videos}
    onEndReachedThreshold={0.2}
    onEndReached={reachedJsx}
    renderItem={itemRender}
    onViewableItemsChanged={onViewRef.current}
    viewabilityConfig={viewConfigRef.current}
    keyExtractor={keyExtractor}
    snapToAlignment={"start"}
    decelerationRate={"fast"}
    snapToInterval={win.height}
    itemHeight={win.height}
    estimatedItemSize={100}
/>

```

**Comment by fortmarek** [comment]
Hey @brunolcarlos 👋 

Could you create a reproducible sample (either on GitHub or on expo's snack) and add steps how to reproduce the issue, detailing the exact specifics of what you are seeing? The code snippet you posted does not include the complete code.

**Comment by naqvitalha** [comment]
@brunolcarlos the incomplete code is making debugging this harder but if I have to guess, it's probably because FlashList doesn't update all the items unless your `data` or `extraData` change.
If there's additional prop rendering depends on, pass it as `extraData`.

**Comment by mfbx9da4** [comment]
I'm also facing this issue. I am setting which items are visible `onScrollEndDrag`.

https://user-images.githubusercontent.com/1690659/188658615-2212bbcf-2c61-4d9a-aeb9-1fd1a340f9b8.mov

**Comment by hirbod** [comment]
I can tell you that Viewability works absolutely fine with FlashList. I am using it in production apps on huge lists. The issues I've came across have been the use of state inside my children and the way I've kept track of my refs. You need to make sure to react to changes within useEffect when using state in your items or use a smarter way, like context to react to visibility inside your items (starting/stopping videos is exactly what I am doing)

I'd recommend you this Gist by @intergalacticspacehighway
https://gist.github.com/intergalacticspacehighway/02a36b05b2236bc750a065833b71c94a

I've ported his approach to FlashList within 5 minutes and its actually the most performant way to react to visibility changes.

**Comment by brunolcarlos** [comment]
With FlatList works, with FlashList not.

**Comment by hirbod** [comment]
As said, it does. You're doing something wrong

**Comment by hirbod** [comment]
Yes, because those lists you've been working with are not recycling. You need to understand that when you recycle views, you need to take care of some circumstances, like stale state (when you are working with state).

If you wan't help, setup up a repro with Snack and I can help you out.

**Comment by brunolcarlos** [comment]
I'm changing the state on every component and it's not working when you
need change the state after the component is mounted.
It's not working with videos and autoplay.



Em dom., 11 de set. de 2022 12:06 PM, Hirbod ***@***.***>
escreveu:

**Comment by hirbod** [comment]
I'll give up. Have fun with FlatList.

**Comment by naqvitalha** [comment]
I'm closing this due to the lack of a sample that we can work with. If you do decide to create one please provide it and we'll look into it.

**Comment by bfricka** [comment]
I can tell you that `extraData` or `data` have no effect on this issue. The handler runs fine when viewability changes due to user interaction, but if the data causes the list to re-render, and this affects viewable items, the handler does not fire.

My list re-renders fine. The item itself renders. The `onViewableItemsChanged` handler does not always fire. I've seen it fire sometimes, but many times it doesn't.

**Comment by brunolcarlos** [comment]
The problem its not if is firing or not, the problem is because the Component still static and nothing change.
Try to create a tiktok feed and make a videos auto play, will not work

**Comment by arthurgeron-work** [comment]
Hey @brunolcarlos , a colleague showed me this issue and I wanted to give you my input on the matter, and to anyone finding this issue.
It's possible to implement a short video feed with autoplay using FlashList, here's one I did myself:

https://github.com/Shopify/flash-list/assets/71399856/ea180f9b-8705-4d61-a5d4-3e6da7e76b00


### There are some key rules when developing short video feeds, here are the most important:

1. Never base your logic on mount/unmount, as FlashList doesn't unmount/mount components, instead, it recycles the same Component instance in "Virtual DOM" with props from a different index of your data array;
2. When saving information about the visible component(s), avoid passing it directly to renderItem, instead, you can use some store outside the React Scope (e.g. zustand), or Flash List's **extraData** which FlashList itself injects into renderItem's props, allowing the method to be declared outside the React scope, which means it won't be instantiated during state changes, meaning better performance;
3. Avoid using useRef values as props, since changes in references don't trigger a new render cycle. Instead use the methods described previously to store data, as a data storage useRef is mostly useful to access/change data within hooks like useEffect without triggering new cycles;
4. Use viewed index + "is focused"(react-navigation) to have proper autoplay/autopause, if you also pause videos during scroll drag you'll have better results.;
5. Make sure all state values get properly reset when main identifiers of your list item component change (e.g. id), this is crucial since FlashList recycles components;
6. Create a very strict set of rules in your `viewabilityConfig`, so videos pause/play perfectly when they're supposed to.

### About "Viewable Items" events:
- It doesn't fire (as far as I remember) without a scroll event, meaning the first time the screen loads, or if you navigate back to the screen, the event won't be fired. Which means it's a good idea to keep it in a store (not a local useState) so that information can be kept until you don't need it anymore;
- The event itself does not trigger new renders, hence storing it in a ref won't trigger new render cycles, hence why autoplay with ref wouldn't work.

I hope this helps, I can't share much code but this should show how practical and simple that implementation can be.

### Viewable Config:
![image](https://github.com/Shopify/flash-list/assets/71399856/19de29d7-b4fa-474c-b8ce-b7a3155d6e0d)

### Viewable Method(stored in zustand store):
![image](https://github.com/Shopify/flash-list/assets/71399856/96ae2a9b-ad14-4019-8dec-b90154fb7e4a)

### List Item Using that for autoplay:
![image](https://github.com/Shopify/flash-list/assets/71399856/0638b384-c42b-4a06-b6e6-9b460a47d501)

**Comment by arthurgeron-work** [comment]
> I can tell you that `extraData` or `data` have no effect on this issue. The handler runs fine when viewability changes due to user interaction, but if the data causes the list to re-render, and this affects viewable items, the handler does not fire.
> 
> My list re-renders fine. The item itself renders. The `onViewableItemsChanged` handler does not always fire. I've seen it fire sometimes, but many times it doesn't.

Some misconceptions here:
- Viewable Items event only gets triggered by scroll events, so this information needs to be kept if you want to maintain position after the order of the data array changes, if you need to maintain position you'd need to use that info alongside scrollToIndex;
- FlashList does not have a way to maintain current position in the array without being manually implemented by the dev

**Comment by Anas-7** [comment]
In case anyone needs help on this issue, there is a solution that worked for me. In my case, I was sending a prop and a callback to change its value to the item rendered in flashlist but I noticed that the value wouldn't change within the item, but it would in the component where I had the flashlist. So the solution was to trigger a re-render that would make sure the items of flashlist receive that change.

Here is a short snippet:
```
const [reRender, setReRender] = useState(false);
const [yourVariableorButtonClick, setYourVariableorButtonClick] = useState(something);


useEffect(() => {
   // In my case I wanted to trigger the re-render only when the value was true
  if(yourVariableorButtonClick)
     setReRender(prev => !prev);
}, [yourVariableorButtonClick]);
```
Then go to your Flashlist component and add the re-render variable to extra data
```
<FlashList
    data={data}
    extraData={reRender}
    renderItem={(item) => (
        <Component
            yourVariableorButtonClick={yourVariableorButtonClick}
            setYourVariableorButtonClick={setYourVariableorButtonClick}
            your_prop={item}
       />
    )}
/>
```

This let me use the viewableItemsConfig and other stuff such as passing the flashlist ref to the items and using scrollToIndex method within the item to scroll to next post, and I imagine it can be done for clicking on buttons too then.

**Comment by hirbod** [comment]
We have a proper fix for this, Nishan will provide a PR for this next week.

**Comment by favazpa** [comment]
@hirbod  do you think this will get merged?.I am also experiencing issues in feed list

**Comment by rahimn20** [comment]
For anyone who is still struggling with this issue, try to wrap your Flashlist in a parent container with flex: 1
