### ISSUE TITLE
onViewableItemsChanged does not register changes in outside data

### ISSUE THREAD

**Issue by Dani-Boy92** [Shopify/flash-list#610]
## Current behavior
Dynamic  data  oustide (a state) the  onViewableItemsChanged function  should be used to run some operations inside of onViewableItemsChanged. However whenever the outside data changes that is not register by the onViewableItemsChanged function, the inital value is always used.

 I have used the useRef and useCallback with and without outside data in the dependency.
```
  const onViewableItemsChanged = useCallback(({ viewableItems }: any) => {
    if (!viewableItems.length) return;

    if (viewableItems[0]?.index === outsideData) {
      // do something, only triggered with the inital state of outsideData
      console.log("match");
    }
  }, []);
```

## Expected behavior
When outside data  changes that should be registered by the onViewableItemsChanged function.

**Comment by naqvitalha** [comment]
Is your renderItem memoized? If yes, remove the memoization and try. We cancel deep renders if renderItem is memoized

**Comment by fortmarek** [comment]
Please, open a new issue with full reproduction steps if the problems persist.

**Comment by ArseniiLyzenko** [comment]
Same problem

**Comment by BouarourMohammed** [comment]
Same Problem

**Comment by Dinkelborg** [comment]
This seems to still be an issue. 
We use Flashlist and our renderItem is *not* memoized, 
we tried handing a state down to the module that uses the flashlist but 
no matter if we wrap the onViewableItemsChanged handler in a useCallback and 
put the prop inside the dependency array or if we use a regular arrow function 
the state never updates inside of onViewableItemsChanged which is a huge problem in 
our case as we need to prevent something from happening while the user scrolls if a certain 
state is true. 

We tried to use a ref instead of the state but to no avail same issue
