### ISSUE TITLE
Unable to test with jest

### ISSUE THREAD

**Issue by ethanneff** [Shopify/flash-list#793]
This does not work https://shopify.github.io/flash-list/docs/testing/

```ts
import "@shopify/flash-list/jestSetup";
```

This works

```ts
jest.mock('@shopify/flash-list', () => {
  const React = require('react')
  const ActualFlashList = jest.requireActual('@shopify/flash-list').FlashList
  return {
    ...jest.requireActual('@shopify/flash-list'),
    FlashList: (props) => (
      <ActualFlashList {...props} estimatedListSize={{ height: 1000, width: 400 }} horizontal={false} />
    ),
  }
})
```

**Comment by fortmarek** [comment]
Please, provide more details or a PR. We use the jest setup in our apps without an issue 🙏

**Comment by adamrichter-star** [comment]
We have the same issue:

We added the following to our existing `jest.setupFilesAfterEnv.ts`:

```ts
import "@shopify/flash-list/jestSetup";
```

and removed our previous mock for FlashList:

```ts
jest.mock('@shopify/flash-list', () => {
  const React = require('react');
  const { FlatList } = require('react-native');

  return {
    FlashList: React.forwardRef((props, ref) => {
      return React.createElement(FlatList, {
        ref: ref,
        ...props,
      });
    }),
  };
});
```

After this change, running our tests triggers the following errors and warnings related to FlashList:

```
console.error
  An update to ForwardRef(FlashList) inside a test was not wrapped in act(...).

console.warn
  An error occurred in the <ForwardRef(FlashList)> component.
```

Our `jest.setupFilesAfterEnv.ts` is correctly integrated in `jest.config.js`:

```js
setupFilesAfterEnv: [
  // ...
  '<rootDir>/jest.setupFilesAfterEnv.ts',
],
```

This indicates that using the official FlashList Jest setup conflicts with our current test setup, likely due to state updates in FlashList not being wrapped in `act(...)`
